import { chromium } from '@playwright/test';
const BASE = 'http://localhost:8081';
const ROUTE = BASE + '/#/ecat-integrations/integration-env-air-station-manager/air-station-manager/index/history_data';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1600, height: 900 }, storageState: 'test-results/.asm-auth.json' });
const page = await ctx.newPage();
await page.goto(ROUTE, { waitUntil: 'networkidle', timeout: 45000 }).catch(e => console.log('goto:', e.message));
await page.waitForTimeout(4000);
console.log('URL:', page.url());
console.log('TITLE:', await page.title());
const body = await page.evaluate(() => document.body.innerText.slice(0, 400));
console.log('BODY:', body);
await page.screenshot({ path: '/tmp/vis2/debug.png' });
await browser.close();
